akka.http.cors {
  allowed-origins = ["*"]
  allowed-headers = ["Content-Type", "Authorization"]
}

akka.javasdk.agent {
  model-provider = "anthropic"

  anthropic {
    provider = "anthropic"
    api-key = ""
    api-key = ${?ANTHROPIC_API_KEY}
    model-name = "claude-haiku-4-5-20251001"
  }
}
